app:
    build: .
    links:
        - postgres
postgres:
    image: postgres
    environment: # FIXME: Use better passwords
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: aliemu
        PGDATA: /var/lib/postgresql/data/pgdata
data:
    image: busybox
    volumes:
        - /var/lib/postgresql/data/pgdata
